apiVersion: v1
kind: Service
metadata:
  name: litellm-image-gen-gateway
  labels:
    app: litellm-image-gen-gateway
    module: image-gen
spec:
  type: NodePort
  selector:
    app: litellm-image-gen-gateway
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30400  # Image generation module on port 30400
